type Token @entity {
    id: ID!
    symbol: String!
    name: String!
    decimals: Int!
    totalSupply: BigInt!
}

enum PoolType {
    V2
    V4
}

type Pool @entity {
    id: ID!
    type: PoolType!
    hookAddress: Bytes!
    token0: Token!
    token1: Token!
    fee: Int!
    tickSpacing: Int!
    createdAtTimestamp: BigInt!
    createdAtBlockNumber: BigInt!

    liquidity: BigInt!
    reserve0: BigInt!
    reserve1: BigInt!

    sqrtPrice: BigInt
    tick: Int

    actions: [Action!]! @derivedFrom(field: "pool")
    snapshots: [TVLSnapshot!]! @derivedFrom(field: "pool")
    positions: [Position!]! @derivedFrom(field: "pool")
}

type User @entity {
    id: ID!
    positions: [Position!]! @derivedFrom(field: "user")
    actions: [Action!]! @derivedFrom(field: "user")
}

type Position @entity {
    id: ID!
    pool: Pool!
    user: User!
    liquidity: BigInt!

    # V4: TODO: Calculating exact underlying reserves for V4 requires complex math based on ticks and current price.
    reserve0: BigInt!
    reserve1: BigInt!

    tickLower: Int
    tickUpper: Int
    tokenId: BigInt!
}

enum ActionType {
    SWAP
    MINT
    BURN
}

type Action @entity {
    id: ID!
    type: ActionType!
    timestamp: BigInt!
    blockNumber: BigInt!
    transactionHash: Bytes!
    pool: Pool!
    user: User!

    amount0: BigInt!
    amount1: BigInt!

    tokenIn: Token
    tokenOut: Token
    amountIn: BigInt
    amountOut: BigInt
    isBuyToken0: Boolean
    isBuyToken1: Boolean
}

type TVLSnapshot @entity {
    id: ID!
    pool: Pool!
    timestamp: BigInt!
    blockNumber: BigInt!
    liquidity: BigInt!
    reserve0: BigInt!
    reserve1: BigInt!
}
