import {
    V2PositionCreated,
    V2PositionModified,
    V2PositionRemoved
} from "../generated/V2PositionHandler/V2PositionHandler"
import { Pool, Position, User } from "../generated/schema"
import { ZERO_BI, ZERO_BD } from "./constants"
import { Address, BigInt, log } from "@graphprotocol/graph-ts"
import { loadOrCreateUser } from "./helpers"
// Import the update function from v2hook.ts to synchronize User TVL
import { updateV2PositionReserves } from "./v2hook"


export function handleV2PositionCreated(event: V2PositionCreated): void {
    let poolId = event.params.poolId.toHexString()
    let pool = Pool.load(poolId)
    if (pool == null) return

    let user = loadOrCreateUser(event.params.owner)
    let tokenId = event.params.tokenId

    // Position ID is the synthetic TokenId generated by V2PositionHandler
    let positionId = tokenId.toString()

    let position = new Position(positionId)
    position.pool = pool.id
    position.user = user.id
    position.tokenId = tokenId

    // LIMITATION: The V2PositionCreated event does not include the initial liquidity amount.
    // We initialize with 0. The liquidity will be updated in the subsequent V2PositionModified event
    // which is emitted immediately after creation in the V2PositionHandler._createPosition function.
    position.liquidity = ZERO_BI
    position.reserve0 = ZERO_BI
    position.reserve1 = ZERO_BI
    position.valueUSD = ZERO_BD

    // V2 positions are full range, tickLower/tickUpper remain null.

    position.save()
}

export function handleV2PositionModified(event: V2PositionModified): void {
    let poolId = event.params.poolId.toHexString()
    let pool = Pool.load(poolId)
    if (pool == null) return

    let tokenId = event.params.tokenId
    let positionId = tokenId.toString()
    let position = Position.load(positionId)

    if (position == null) {
        log.warning("V2 Position Modified before creation event processed: {}", [positionId])
        // This might happen if the Created event hasn't been processed yet (e.g. same block).
        // We rely on the Created handler to initialize the position.
        return
    }

    let liquidityDelta = event.params.liquidityDelta

    // Update position liquidity
    position.liquidity = position.liquidity.plus(liquidityDelta)

    // Update pool total liquidity (Total LP Supply for V2)
    pool.liquidity = pool.liquidity.plus(liquidityDelta)
    pool.save()

    // Update position reserves based on new liquidity share and current pool reserves
    // Note: Pool reserves (pool.reserve0/1) are updated via the Sync event, which happens in the same transaction.
    // If Sync is processed before this handler, the reserves are up-to-date.
    updateV2PositionReserves(position, pool)
}

export function handleV2PositionRemoved(event: V2PositionRemoved): void {
    let poolId = event.params.poolId.toHexString()
    let pool = Pool.load(poolId)
    if (pool == null) return

    let tokenId = event.params.tokenId
    let positionId = tokenId.toString()
    let position = Position.load(positionId)

    if (position == null) return

    // Update pool total liquidity by subtracting the removed position's liquidity
    pool.liquidity = pool.liquidity.minus(position.liquidity)
    pool.save()

    // Mark the position as closed (liquidity 0)
    position.liquidity = ZERO_BI
    updateV2PositionReserves(position, pool)
    // Alternatively, the entity could be removed from storage, but keeping it might be useful for historical tracking.
}